{% set name = "apispec-webframeworks" %}
{% set version = "0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apispec-webframeworks-{{ version }}.tar.gz
  sha256: 0db35b267914b3f8c562aca0261957dbcb4176f255eacc22520277010818dcf3

build:
  number: 4
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - apispec >=2.0.0
    - python >=3.6

test:
  imports:
    - apispec_webframeworks
    - apispec_webframeworks.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/marshmallow-code/apispec-webframeworks
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Web framework plugins for apispec."
  doc_url: https://pypi.org/project/apispec-webframeworks/#description
  dev_url: https://github.com/marshmallow-code/apispec-webframeworks

extra:
  recipe-maintainers:
    - ndmaxar
    - oblute
    - rluria14
